### PR TITLE
Fixed path to packages reference

### PR DESCRIPTION
**Pull request by Marusyk**
This solution build is failed because the path is wrong. The fix helps to build the solution on others machine

### CODE REVIEW

**Comment by Marusyk** [comment]
It has been about 5 month since the latest update. @pavel-b-novikov  Is this project dead?

**Comment by pavel-b-novikov** [comment]
It is not project at all. It is just piece of demo code

**Comment by Marusyk** [comment]
@pavel-b-novikov so, you're not gonna support it, right?

**Comment by pavel-b-novikov** [comment]
Exactly. Maybe later

**Pull request closed without merging**
